services:
  api:
    build:
      context: .
      dockerfile: Dockerfile
    command: ["uvicorn", "api.main:app", "--host", "0.0.0.0", "--port", "8000", "--reload"]
    volumes:
      - .:/app
    ports:
      - "8000:8000"
    env_file:
      - .env
    networks:
      - app-network

  streamlit:
    build:
      context: .
      dockerfile: Dockerfile
    command: ["streamlit", "run", "streamlit/app.py", "--server.port", "5000", "--server.address", "0.0.0.0"]
    volumes:
      - .:/app
    ports:
      - "5000:5000"
    env_file:
      - .env
    depends_on:
      - api
    networks:
      - app-network

networks:
  app-network:
    driver: bridge
